# Generated by Django 4.0.4 on 2022-04-24 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('vendor', models.CharField(max_length=255, verbose_name='Производитель')),
                ('vendor_code', models.CharField(max_length=255, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('last_upd_date', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('warranty', models.IntegerField(choices=[(0, 'Отсутсвует'), (1, 'Стандартная'), (2, 'Особая'), (3, 'С возможностью продления')], default=0, verbose_name='Тип гарантии')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Товар в каталоге',
                'verbose_name_plural': 'Товары в каталоге',
                'ordering': ['-last_upd_date', 'vendor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Моб. телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('discount', models.IntegerField(choices=[(0, 'Отсутствует'), (1, 'Стандартная'), (2, 'Постоянный покупатель'), (3, 'Промо-акция'), (4, 'Особый клиент')], default=0, verbose_name='Тип скидки')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Не указано'), (1, 'Женщина'), (2, 'Мужчина')], null=True, verbose_name='Пол')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Работа/Специальность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('upd_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['upd_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.department', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('gender', models.IntegerField(choices=[(0, 'Не указано'), (1, 'Женщина'), (2, 'Мужчина')], default=0, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('role', models.IntegerField(choices=[(0, 'Не указана'), (1, 'Консультант'), (2, 'Продавец-консультант'), (3, 'Системный администратор'), (4, 'Администратор'), (5, 'Кассир')], default=0, verbose_name='Должность')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicshop.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('upd_time', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('status', models.IntegerField(choices=[(0, 'Не указан'), (1, 'Инициализация'), (2, 'Открыт'), (3, 'Закрыт'), (4, 'Ошибка'), (5, 'В стадии обсуждения'), (6, 'Отменен'), (7, 'Другое')], default=1, verbose_name='Статус')),
                ('payment_type', models.IntegerField(choices=[(0, 'Не указан'), (1, 'Наличные'), (2, 'Банковская карта'), (3, 'Другое')], default=1, verbose_name='Тип оплаты')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicshop.client', verbose_name='Покупатель')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicshop.staff', verbose_name='Сотрдуник')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['upd_time'],
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(0, 'Не указано'), (1, 'Склад'), (2, 'Витрина')], default=0, verbose_name='Тип расположения')),
                ('location_description', models.TextField(blank=True, null=True, verbose_name='Описание расположения')),
                ('actual', models.BooleanField(default=False, verbose_name='Доступность позиции')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicshop.catalog', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар на складе',
                'verbose_name_plural': 'Товары на складе',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('cat_id', models.IntegerField(verbose_name='Идентификатор (Будет заменен на slug)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='catalog_images', verbose_name='Фото')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicshop.catalog', verbose_name='Товар')),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicshop.category', verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicshop.good', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicshop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
