# Generated by Django 4.0.4 on 2022-04-24 08:24

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0002_alter_catalogimages_options_remove_category_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
